max_results = 30

file_path = "./docs/index.md"

[[topics]]
name = "交易"
filters = ["Trading"]

[[topics]]
name = "注意力机制"
filters = ["Attention Mechanism"]

[[topics]]
name = "背景差分"
filters = ["Background Subtraction"]
