title: Daily Arxiv
author: Yiguang
email: yiguang20@yandex.com
description: >
  ðŸŽ“Arxiv for target keywords

github_username: yiguang20

remote_theme: jekyll/minima@v2.5.1

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag
